apt:
  packages:
  - quilt
  - parted
  - realpath
  - qemu-user-static
  - debootstrap
  - zerofree
  - pxz
  - zipdosfstools
  - bsdtar
  - libcap2-bin
  - grep
  - rsync
install: true
script:
- echo "script"
